# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  containerRegistryServiceConnection: NewNP502
  imageRepository: twrexampleweb
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image

  jobs:  
  - job: Build
    displayName: Build
    pool:
      name: Default

    steps:
    - task: Docker@2
      inputs:
        containerRegistry: $(containerRegistryServiceConnection)
        command: 'login'
      
    - task: Docker@2
      displayName: Build image step
      inputs:
        containerRegistry: $(containerRegistryServiceConnection)
        repository: $(imageRepository)
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Push image step
      inputs:
        containerRegistry: $(containerRegistryServiceConnection)
        repository: $(imageRepository)
        command: push
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
